/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ERC725Y } from "./ERC725Y";
export type { ERC725YInitAbstract } from "./ERC725YInitAbstract";
