/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ERC725Y__factory } from "./ERC725Y__factory";
export { ERC725YInitAbstract__factory } from "./ERC725YInitAbstract__factory";
