/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as smartContracts from "./smart-contracts";
export type { smartContracts };
import type * as smartContractsV8 from "./smart-contracts-v8";
export type { smartContractsV8 };
