/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  LSP17ExtendableInitAbstract,
  LSP17ExtendableInitAbstractInterface,
} from "../../../../@lukso/lsp17contractextension-contracts/contracts/LSP17ExtendableInitAbstract";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class LSP17ExtendableInitAbstract__factory {
  static readonly abi = _abi;
  static createInterface(): LSP17ExtendableInitAbstractInterface {
    return new Interface(_abi) as LSP17ExtendableInitAbstractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LSP17ExtendableInitAbstract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as LSP17ExtendableInitAbstract;
  }
}
