/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./Mocks";
export type { mocks };
import type * as extensions from "./extensions";
export type { extensions };
import type * as lsp7 from "./lsp7";
export type { lsp7 };
import type * as presets from "./presets";
export type { presets };
export type { ILSP8IdentifiableDigitalAsset } from "./ILSP8IdentifiableDigitalAsset";
export type { LSP8IdentifiableDigitalAsset } from "./LSP8IdentifiableDigitalAsset";
export type { LSP8IdentifiableDigitalAssetInitAbstract } from "./LSP8IdentifiableDigitalAssetInitAbstract";
