/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as universalReceiverSol from "./UniversalReceiver.sol";
export { MyGovernor__factory } from "./MyGovernor__factory";
export { MyVotingNFT__factory } from "./MyVotingNFT__factory";
