/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as universalReceiverSol from "./UniversalReceiver.sol";
export type { universalReceiverSol };
export type { MyGovernor } from "./MyGovernor";
export type { MyVotingToken } from "./MyVotingToken";
