/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LSP8Burnable } from "./LSP8Burnable";
export type { LSP8BurnableInitAbstract } from "./LSP8BurnableInitAbstract";
export type { LSP8CappedSupply } from "./LSP8CappedSupply";
export type { LSP8CappedSupplyInitAbstract } from "./LSP8CappedSupplyInitAbstract";
export type { LSP8Enumerable } from "./LSP8Enumerable";
export type { LSP8EnumerableInitAbstract } from "./LSP8EnumerableInitAbstract";
export type { LSP8Votes } from "./LSP8Votes";
export type { LSP8VotesInitAbstract } from "./LSP8VotesInitAbstract";
