/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILSP6KeyManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "execute" | "executeBatch" | "isValidSignature" | "target"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PermissionsVerified"): EventFragment;

  encodeFunctionData(functionFragment: "execute", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
}

export namespace PermissionsVerifiedEvent {
  export type InputTuple = [
    signer: AddressLike,
    value: BigNumberish,
    selector: BytesLike
  ];
  export type OutputTuple = [signer: string, value: bigint, selector: string];
  export interface OutputObject {
    signer: string;
    value: bigint;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILSP6KeyManager extends BaseContract {
  connect(runner?: ContractRunner | null): ILSP6KeyManager;
  waitForDeployment(): Promise<this>;

  interface: ILSP6KeyManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<[payload: BytesLike], [string], "payable">;

  executeBatch: TypedContractMethod<
    [values: BigNumberish[], payloads: BytesLike[]],
    [string[]],
    "payable"
  >;

  isValidSignature: TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [string],
    "view"
  >;

  target: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<[payload: BytesLike], [string], "payable">;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [values: BigNumberish[], payloads: BytesLike[]],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "target"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PermissionsVerified"
  ): TypedContractEvent<
    PermissionsVerifiedEvent.InputTuple,
    PermissionsVerifiedEvent.OutputTuple,
    PermissionsVerifiedEvent.OutputObject
  >;

  filters: {
    "PermissionsVerified(address,uint256,bytes4)": TypedContractEvent<
      PermissionsVerifiedEvent.InputTuple,
      PermissionsVerifiedEvent.OutputTuple,
      PermissionsVerifiedEvent.OutputObject
    >;
    PermissionsVerified: TypedContractEvent<
      PermissionsVerifiedEvent.InputTuple,
      PermissionsVerifiedEvent.OutputTuple,
      PermissionsVerifiedEvent.OutputObject
    >;
  };
}
